# Generated by Django 4.2.13 on 2024-08-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloDatafont',
            fields=[
                ('id_modulo_datafont', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_font', models.CharField(blank=True, db_comment='Se a conexão e de Origem ou Destino', max_length=20, null=True)),
                ('servername', models.CharField(blank=True, max_length=150, null=True)),
                ('serverip', models.CharField(blank=True, max_length=150, null=True)),
                ('sgbp', models.CharField(blank=True, max_length=50, null=True)),
                ('databasename', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('psw', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('stringconection', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_datafont',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloDb',
            fields=[
                ('id_modulo_db', models.AutoField(primary_key=True, serialize=False)),
                ('base_modulo', models.CharField(blank=True, max_length=50, null=True)),
                ('base_name', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloDbTable',
            fields=[
                ('id_modulo_db_table', models.AutoField(primary_key=True, serialize=False)),
                ('name_table', models.CharField(blank=True, max_length=50, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_db_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloDbTableModuloEtl',
            fields=[
                ('id_modulo_db_table_modulo_etl', models.AutoField(primary_key=True, serialize=False)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_db_table_modulo_etl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloEtl',
            fields=[
                ('id_modulo_etl', models.AutoField(primary_key=True, serialize=False)),
                ('etl_name', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_etl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloEtlDatafontOrigem',
            fields=[
                ('id_modulo_etl_datafont_origem', models.AutoField(primary_key=True, serialize=False)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_etl_datafont_origem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloEtlScript',
            fields=[
                ('id_modulo_etl_script', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('codigofont', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dependencia', models.IntegerField(blank=True, null=True)),
                ('exec_paralelo', models.TextField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('order_exec', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_etl_script',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloIntegridadeEtl',
            fields=[
                ('id_modulo_integridade_etl', models.AutoField(primary_key=True, serialize=False)),
                ('tl_registro_pl', models.IntegerField()),
                ('tl_rg_ativos_pl', models.IntegerField()),
                ('tl_rg_desativados_pl', models.IntegerField()),
                ('tl_rg_novos_up', models.IntegerField()),
                ('tl_rg_ativados_up', models.IntegerField()),
                ('tl_rg_desativados_up', models.IntegerField()),
                ('tl_rg_outras_up', models.IntegerField()),
                ('tl_registro', models.IntegerField()),
                ('tl_rg_ativos', models.IntegerField()),
                ('tl_rg_desativados', models.IntegerField()),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_integridade_etl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloJobs',
            fields=[
                ('id_modulo_jobs', models.AutoField(primary_key=True, serialize=False)),
                ('nomejobs', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloJobsSchedule',
            fields=[
                ('id_modulo_jobs_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('nomeschedule', models.CharField(blank=True, max_length=150, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_jobs_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloLogs',
            fields=[
                ('id_modulo_logs', models.AutoField(primary_key=True, serialize=False)),
                ('executado', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_start', models.DateTimeField(blank=True, null=True)),
                ('dt_end', models.DateTimeField(blank=True, null=True)),
                ('job_status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('log_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloServerRun',
            fields=[
                ('id_modulo_server_run', models.AutoField(primary_key=True, serialize=False)),
                ('nomeconexao', models.CharField(blank=True, max_length=150, null=True)),
                ('server', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo_server_run',
                'managed': False,
            },
        ),
    ]
