# Generated by Django 4.2.13 on 2024-09-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_integrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwModuloDatafont',
            fields=[
                ('id_modulo_datafont', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_font', models.CharField(blank=True, db_comment='Se a conexão e de Origem ou Destino', max_length=20, null=True)),
                ('servername', models.CharField(blank=True, max_length=150, null=True)),
                ('serverip', models.CharField(blank=True, max_length=150, null=True)),
                ('sgbp', models.CharField(blank=True, max_length=50, null=True)),
                ('databasename', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('psw', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('stringconection', models.TextField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_modulo_datafont',
                'managed': False,
            },
        ),
    ]
