# Generated by Django 4.2.11 on 2024-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id_applications', models.IntegerField(primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=20, null=True)),
                ('name0', models.CharField(blank=True, max_length=150, null=True)),
                ('ad_site_name0', models.CharField(blank=True, max_length=50, null=True)),
                ('user_name0', models.CharField(blank=True, max_length=250, null=True)),
                ('publisher0', models.CharField(blank=True, max_length=250, null=True)),
                ('displayname0', models.TextField(blank=True, null=True)),
                ('version0', models.CharField(blank=True, max_length=50, null=True)),
                ('dhupdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkAdapter',
            fields=[
                ('id_network_adapter', models.IntegerField(primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=20, null=True)),
                ('adaptertype0', models.TextField(blank=True, null=True)),
                ('productname0', models.TextField(blank=True, null=True)),
                ('macaddress0', models.TextField(blank=True, null=True)),
                ('dhcpenabled0', models.BooleanField(blank=True, null=True)),
                ('dhcpserver0', models.TextField(blank=True, null=True)),
                ('dnsdomain0', models.TextField(blank=True, null=True)),
                ('dnshostname0', models.TextField(blank=True, null=True)),
                ('ipaddress0', models.TextField(blank=True, null=True)),
                ('deviceid0', models.IntegerField(blank=True, null=True)),
                ('ipenabled0', models.BooleanField(blank=True, null=True)),
                ('ipsubnet0', models.TextField(blank=True, null=True)),
                ('servicename0', models.TextField(blank=True, null=True)),
                ('dhupdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'network_adapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerHost',
            fields=[
                ('id_server_host', models.IntegerField(primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=20, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=256, null=True)),
                ('dominio', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('machinetype', models.CharField(blank=True, max_length=50, null=True)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('bioserialnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=256, null=True)),
                ('ospkversao', models.CharField(blank=True, max_length=50, null=True)),
                ('osversao', models.CharField(blank=True, max_length=50, null=True)),
                ('nserie', models.CharField(blank=True, max_length=256, null=True)),
                ('totalphysicalmemory', models.IntegerField(blank=True, null=True)),
                ('cpufabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('cpumodelo', models.CharField(blank=True, max_length=100, null=True)),
                ('cpusockets', models.IntegerField(blank=True, null=True)),
                ('corespersocket', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('clientsccm', models.CharField(blank=True, max_length=50, null=True)),
                ('dhupdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.IntegerField(primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=20, null=True)),
                ('name0', models.CharField(blank=True, max_length=150, null=True)),
                ('companyname', models.CharField(blank=True, max_length=250, null=True)),
                ('productname', models.CharField(blank=True, max_length=250, null=True)),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('fileversion', models.CharField(blank=True, max_length=250, null=True)),
                ('filepath', models.TextField(blank=True, null=True)),
                ('dhupdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vmdisk',
            fields=[
                ('id_vmdisk', models.IntegerField(primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=20, null=True)),
                ('groupid', models.IntegerField(blank=True, null=True)),
                ('agentid', models.IntegerField(blank=True, null=True)),
                ('tmstamp', models.DateTimeField(blank=True, null=True)),
                ('caption0', models.CharField(blank=True, max_length=150, null=True)),
                ('description0', models.CharField(blank=True, max_length=50, null=True)),
                ('deviceid0', models.CharField(blank=True, max_length=50, null=True)),
                ('index0', models.IntegerField(blank=True, null=True)),
                ('interfacetype0', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer0', models.CharField(blank=True, max_length=50, null=True)),
                ('mediatype0', models.CharField(blank=True, max_length=50, null=True)),
                ('model0', models.CharField(blank=True, max_length=50, null=True)),
                ('name0', models.CharField(blank=True, max_length=100, null=True)),
                ('partitions0', models.IntegerField(blank=True, null=True)),
                ('pnpdeviceid0', models.CharField(blank=True, max_length=256, null=True)),
                ('scsibus0', models.IntegerField(blank=True, null=True)),
                ('scsilogicalunit0', models.IntegerField(blank=True, null=True)),
                ('scsiport0', models.IntegerField(blank=True, null=True)),
                ('scsitargetid0', models.IntegerField(blank=True, null=True)),
                ('size0', models.FloatField(blank=True, null=True)),
                ('systemname0', models.CharField(blank=True, max_length=50, null=True)),
                ('dhupdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vmdisk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwSoftware',
            fields=[
                ('id_software', models.IntegerField(primary_key=True, serialize=False)),
                ('resourceid', models.CharField(blank=True, max_length=20, null=True)),
                ('serverhost', models.CharField(blank=True, max_length=150, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=250, null=True)),
                ('software', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'vw_software',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwSoftwareFile',
            fields=[
                ('id_software', models.IntegerField(primary_key=True, serialize=False)),
                ('fileexec', models.CharField(blank=True, max_length=250, null=True)),
                ('version', models.CharField(blank=True, max_length=250, null=True)),
                ('fillocalinstallepath', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_software_file',
                'managed': False,
            },
        ),
    ]
