# Generated by Django 4.2.13 on 2024-08-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sds_sccm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='NetworkAdapter',
        ),
        migrations.DeleteModel(
            name='ServerHost',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
        migrations.DeleteModel(
            name='Vmdisk',
        ),
        migrations.DeleteModel(
            name='VwSoftware',
        ),
        migrations.DeleteModel(
            name='VwSoftwareFile',
        ),
    ]
