# Generated by Django 4.2.11 on 2024-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basededados',
            fields=[
                ('idbasededados', models.AutoField(primary_key=True, serialize=False)),
                ('idtrilha', models.IntegerField(blank=True, null=True)),
                ('basededados', models.CharField(blank=True, max_length=150, null=True)),
                ('dbowner', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basededados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bdtabela',
            fields=[
                ('idbdtabela', models.AutoField(primary_key=True, serialize=False)),
                ('schema_name', models.CharField(blank=True, max_length=128, null=True)),
                ('table_name', models.CharField(blank=True, max_length=128, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bdtabela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bdtamanho',
            fields=[
                ('idbdtamanho', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.FloatField(blank=True, null=True)),
                ('datatimer', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bdtamanho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('idcluster', models.AutoField(primary_key=True, serialize=False)),
                ('clustername', models.CharField(blank=True, max_length=60, null=True)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cluster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clusterno',
            fields=[
                ('idclusterno', models.AutoField(primary_key=True, serialize=False)),
                ('id_serverhost', models.IntegerField()),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clusterno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clustertipo',
            fields=[
                ('idclustertipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clustertipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('idinstancia', models.AutoField(primary_key=True, serialize=False)),
                ('id_serverhost', models.IntegerField()),
                ('id_trilha', models.IntegerField()),
                ('instancia', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd', models.CharField(blank=True, max_length=30, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('conectstring', models.CharField(blank=True, max_length=255, null=True)),
                ('porta', models.FloatField(blank=True, null=True)),
                ('cluster', models.BooleanField(blank=True, null=True)),
                ('versao', models.CharField(blank=True, max_length=255, null=True)),
                ('productversion', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('funcaoserver', models.CharField(blank=True, max_length=100, null=True)),
                ('sobreadministracao', models.CharField(blank=True, max_length=100, null=True)),
                ('memoryconfig', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cpu', models.IntegerField(blank=True, null=True)),
                ('estanciaativo', models.BooleanField(blank=True, null=True)),
                ('startinstancia', models.DateTimeField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('status_bd', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'instancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciaPg',
            fields=[
                ('idinstancia_pg', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('setting', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instancia_pg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('idlogins', models.AutoField(primary_key=True, serialize=False)),
                ('loginname', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo_login', models.CharField(blank=True, max_length=30, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginsDatabase',
            fields=[
                ('idloginsdb', models.AutoField(primary_key=True, serialize=False)),
                ('acessement', models.JSONField(blank=True, null=True)),
                ('tipo_login', models.CharField(blank=True, max_length=30, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logins_database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginsInstancia',
            fields=[
                ('idloginsin', models.AutoField(primary_key=True, serialize=False)),
                ('acessement', models.JSONField(blank=True, null=True)),
                ('tipo_login', models.CharField(blank=True, max_length=30, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logins_instancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serverdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_serverhost', models.IntegerField(blank=True, null=True)),
                ('id_trilha', models.IntegerField(blank=True, null=True)),
                ('trilha', models.CharField(blank=True, max_length=60, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('hostname', models.CharField(blank=True, max_length=60, null=True)),
                ('dep', models.CharField(blank=True, max_length=20, null=True)),
                ('regiao', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('unidade', models.TextField(blank=True, null=True)),
                ('fisicovm', models.CharField(blank=True, max_length=20, null=True)),
                ('sistemaoperaciona', models.CharField(blank=True, max_length=200, null=True)),
                ('ipaddress', models.CharField(blank=True, max_length=250, null=True)),
                ('portconect', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('versao', models.CharField(blank=True, max_length=350, null=True)),
                ('cpu', models.BigIntegerField(blank=True, null=True)),
                ('memoryram', models.BigIntegerField(blank=True, null=True)),
                ('ad', models.BooleanField(blank=True, null=True)),
                ('or_ad', models.BooleanField(blank=True, null=True)),
                ('sccm', models.BooleanField(blank=True, null=True)),
                ('or_sccm', models.BooleanField(blank=True, null=True)),
                ('nx', models.BooleanField(blank=True, null=True)),
                ('or_nx', models.BooleanField(blank=True, null=True)),
                ('vw', models.BooleanField(blank=True, null=True)),
                ('or_vw', models.BooleanField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'serverdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbcoluna',
            fields=[
                ('idtbcoluna', models.AutoField(primary_key=True, serialize=False)),
                ('colunn_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ordenal_positon', models.IntegerField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=128, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbcoluna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbindex',
            fields=[
                ('idtbindex', models.AutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(blank=True, max_length=255, null=True)),
                ('index_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbindex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trilha', models.IntegerField(blank=True, null=True)),
                ('trilha', models.CharField(blank=True, max_length=60, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'trilha',
                'managed': False,
            },
        ),
    ]
