# Generated by Django 4.2.11 on 2024-05-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vw_basededados',
            fields=[
                ('idbasededados', models.AutoField(primary_key=True, serialize=False)),
                ('id_serverhost', models.IntegerField()),
                ('idinstancia', models.IntegerField(blank=True, null=True)),
                ('idtrilha', models.IntegerField(blank=True, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('servidor', models.CharField(blank=True, max_length=150, null=True)),
                ('hostname', models.CharField(blank=True, max_length=60, null=True)),
                ('instancia', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd', models.CharField(blank=True, max_length=30, null=True)),
                ('basededados', models.CharField(blank=True, max_length=150, null=True)),
                ('tamanho', models.FloatField(blank=True, null=True)),
                ('dbowner', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('dhcriacao', models.DateTimeField(blank=True, null=True)),
                ('dhalteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_basededados',
                'managed': False,
            },
        ),
    ]
