# Generated by Django 5.0.3 on 2024-04-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aqua2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.CharField(max_length=50, verbose_name='content')),
                ('app_name', models.CharField(max_length=50, verbose_name='app_name')),
            ],
        ),
    ]
