# Generated by Django 4.2.13 on 2024-08-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hists',
            fields=[
                ('id_hist', models.AutoField(primary_key=True, serialize=False)),
                ('itemids', models.IntegerField(blank=True, null=True)),
                ('clock', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('hostid', models.IntegerField(primary_key=True, serialize=False)),
                ('id_server_host', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('hostid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTbServerhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_serverhost', models.IntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'master_tb_serverhost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('id_trend', models.AutoField(primary_key=True, serialize=False)),
                ('itemids', models.IntegerField(blank=True, null=True)),
                ('clock', models.DateTimeField()),
                ('num', models.IntegerField(blank=True, null=True)),
                ('value_min', models.FloatField(blank=True, null=True)),
                ('value_avg', models.FloatField(blank=True, null=True)),
                ('value_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwItemsServerHost',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('hostid', models.IntegerField()),
                ('id_server_host', models.IntegerField()),
                ('server_host', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('monitor', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_items_host',
                'managed': False,
            },
        ),
    ]
