# Generated by Django 4.2.13 on 2024-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_zabbix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistsDia',
            fields=[
                ('id_hist_dia', models.AutoField(primary_key=True, serialize=False)),
                ('itemids', models.IntegerField(blank=True, null=True)),
                ('clock', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hists_dia',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vwitemsserverhost',
            options={'managed': False, 'ordering': ['-monitor', 'name']},
        ),
    ]
