# Generated by Django 4.2.11 on 2024-05-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdComputer',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('dnshostname', models.TextField(blank=True, null=True)),
                ('samaccountname', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectcategory', models.TextField(blank=True, null=True)),
                ('objectclass', models.TextField(blank=True, null=True)),
                ('operatingsystem', models.TextField(blank=True, null=True)),
                ('operatingsystemversion', models.TextField(blank=True, null=True)),
                ('distinguishedname', models.TextField(blank=True, null=True)),
                ('whencreated', models.DateTimeField(blank=True, null=True)),
                ('whenchanged', models.DateTimeField(blank=True, null=True)),
                ('lastlogontimestamp', models.DateTimeField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_computer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdComputerDns',
            fields=[
                ('sid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('insert', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_computer_dns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdContact',
            fields=[
                ('name', models.BigAutoField(primary_key=True, serialize=False)),
                ('displayname', models.CharField(blank=True, max_length=100, null=True)),
                ('mailnickname', models.CharField(blank=True, max_length=100, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('memberof', models.TextField(blank=True, null=True)),
                ('distinguishedname', models.TextField(blank=True, null=True)),
                ('objectcategory', models.TextField(blank=True, null=True)),
                ('objectclass', models.TextField(blank=True, null=True)),
                ('whencreated', models.DateTimeField(blank=True, null=True)),
                ('whenchanged', models.DateTimeField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdDomainController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dnshostname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('operatingsystem', models.CharField(blank=True, max_length=100, null=True)),
                ('operatingsystemversion', models.TextField(blank=True, null=True)),
                ('serverreferencebl', models.TextField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_domain_controller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdGpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(blank=True, max_length=100, null=True)),
                ('displayname', models.TextField(blank=True, null=True)),
                ('distinguishedname', models.TextField(blank=True, null=True)),
                ('showinadvancedviewonly', models.TextField(blank=True, null=True)),
                ('versionnumber', models.BigIntegerField(blank=True, null=True)),
                ('whencreated', models.DateTimeField(blank=True, null=True)),
                ('whenchanged', models.DateTimeField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_gpo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectsid', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('samaccountname', models.TextField(blank=True, null=True)),
                ('member', models.TextField(blank=True, null=True)),
                ('memberof', models.TextField(blank=True, null=True)),
                ('distinguishedname', models.TextField(blank=True, null=True)),
                ('objectcategory', models.TextField(blank=True, null=True)),
                ('objectclass', models.TextField(blank=True, null=True)),
                ('whencreated', models.DateTimeField(blank=True, null=True)),
                ('whenchanged', models.DateTimeField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdGroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupmember', models.TextField(blank=True, null=True)),
                ('samaccountname', models.TextField(blank=True, null=True)),
                ('insert', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_group_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdOu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('objectcategory', models.TextField(blank=True, null=True)),
                ('objectclass', models.TextField(blank=True, null=True)),
                ('distinguishedname', models.TextField(blank=True, null=True)),
                ('whencreated', models.DateTimeField(blank=True, null=True)),
                ('whenchanged', models.DateTimeField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_ou',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdUser',
            fields=[
                ('objectsid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('displayname', models.TextField(blank=True, null=True)),
                ('samaccountname', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectcategory', models.TextField(blank=True, null=True)),
                ('objectclass', models.TextField(blank=True, null=True)),
                ('employeetype', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('physicaldeliveryofficename', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('distinguishedname', models.TextField(blank=True, null=True)),
                ('memberof', models.TextField(blank=True, null=True)),
                ('whencreated', models.DateTimeField(blank=True, null=True)),
                ('whenchanged', models.DateTimeField(blank=True, null=True)),
                ('accountexpires', models.DateTimeField(blank=True, null=True)),
                ('badpasswordtime', models.DateTimeField(blank=True, null=True)),
                ('pwdlastset', models.DateTimeField(blank=True, null=True)),
                ('lastlogontimestamp', models.DateTimeField(blank=True, null=True)),
                ('lastlogon', models.DateTimeField(blank=True, null=True)),
                ('badpwdcount', models.BigIntegerField(blank=True, null=True)),
                ('lockouttime', models.BigIntegerField(blank=True, null=True)),
                ('enabled', models.TextField(blank=True, null=True)),
                ('useraccountcontrol', models.BigIntegerField(blank=True, null=True)),
                ('lastupdateetl', models.DateTimeField(blank=True, null=True)),
                ('insert', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ad_user',
                'managed': False,
            },
        ),
    ]
