# Generated by Django 4.2.11 on 2024-05-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sds_active_directory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdComputer',
        ),
        migrations.DeleteModel(
            name='AdComputerDns',
        ),
        migrations.DeleteModel(
            name='AdContact',
        ),
        migrations.DeleteModel(
            name='AdDomainController',
        ),
        migrations.DeleteModel(
            name='AdGpo',
        ),
        migrations.DeleteModel(
            name='AdGroup',
        ),
        migrations.DeleteModel(
            name='AdGroupUser',
        ),
        migrations.DeleteModel(
            name='AdOu',
        ),
        migrations.DeleteModel(
            name='AdUser',
        ),
    ]
